//! Compute SRI (subresource integrity) hashes for vendored client assets at
//! build time. The hashes are baked into `OUT_DIR/sri.rs` as `pub const`s and
//! included via `src/sri.rs`; templates render them into `<script integrity>`
//! attributes.
//!
//! Only assets loaded as static `<script type="module" src=…>` benefit from
//! `<script integrity>`. Dynamic `import()` calls (e.g. the per-page zim_wasm
//! loads) need an import map for browser-side SRI enforcement — out of scope
//! for the v1 baking pass.

use std::path::PathBuf;

use base64::Engine;
use sha2::{Digest, Sha384};

fn main() {
    let out_dir = PathBuf::from(std::env::var("OUT_DIR").expect("OUT_DIR set by cargo"));
    let mut rs = String::new();
    rs.push_str("// AUTO-GENERATED by build.rs. Do not edit.\n\n");

    for (name, rel_path) in [
        ("DATASTAR_SRI", "static/vendor/datastar.min.js"),
        ("ZIM_WASM_SRI", "static/vendor/zim-wasm/zim_wasm.js"),
    ] {
        println!("cargo:rerun-if-changed={rel_path}");
        let value = match std::fs::read(rel_path) {
            Ok(bytes) => {
                let mut hasher = Sha384::new();
                hasher.update(&bytes);
                let digest = hasher.finalize();
                format!(
                    "sha384-{}",
                    base64::engine::general_purpose::STANDARD.encode(digest)
                )
            }
            Err(_) => {
                // Missing vendor file — leave the const as an empty string so
                // the template still compiles. The HTML will render an empty
                // integrity attribute, which browsers treat as no integrity
                // check. Vendor-bump procedure (`make hub` etc.) will create
                // the file and re-run the build.
                String::new()
            }
        };
        rs.push_str(&format!("pub const {name}: &str = \"{value}\";\n"));
    }

    std::fs::write(out_dir.join("sri.rs"), rs).expect("write OUT_DIR/sri.rs");
}
