//! Iroh transport for the sync protocol.
//!
//! - [`SyncProtocol`] implements `iroh::protocol::ProtocolHandler` —
//!   it accepts incoming bidirectional streams under [`ALPN`], parses
//!   the wire request, dispatches to the coordinator via
//!   [`dispatch_request`](crate::wire_protocol::dispatch_request),
//!   and writes back the reply.
//! - [`IrohPeerSender`] holds the outbound `Endpoint`; the typed
//!   `PeerSender` impl with one `send_<variant>` method per wire
//!   message is generated by the `wire_protocol!` macro in
//!   `crate::wire_protocol`.
//!
//! Wire format is bincode-serialized
//! [`WireRequest`](crate::wire_protocol::WireRequest) /
//! [`WireReply`](crate::wire_protocol::WireReply), length-framed by
//! the underlying QUIC stream (the responder reads to EOF, the
//! initiator reads to EOF after `send.finish()`).

use std::sync::Arc;

use anyhow::{anyhow, Context};
use futures::future::BoxFuture;

use zim_core::iroh::{self, AcceptError, Connection, Endpoint, ProtocolHandler};
use zim_crypto::PublicKey;

use crate::coordinator::SyncCoordinator;
use crate::wire_protocol::{dispatch_request, WireReply, WireRequest};
use zim_core::vault::VaultLog;

/// ALPN identifier for the Zim peer sync protocol.
pub const ALPN: &[u8] = b"/zim-peer/0";

const MAX_MESSAGE: usize = 1024 * 1024;

// ─── Responder: ProtocolHandler ────────────────────────────────────

/// Iroh `ProtocolHandler` that routes incoming sync messages into a
/// [`SyncCoordinator`].
pub struct SyncProtocol<L: VaultLog + Clone + 'static>
where
    L::Error: std::error::Error + Send + Sync + 'static,
{
    coord: Arc<SyncCoordinator<L>>,
}

impl<L: VaultLog + Clone + 'static> std::fmt::Debug for SyncProtocol<L>
where
    L::Error: std::error::Error + Send + Sync + 'static,
{
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("SyncProtocol").finish_non_exhaustive()
    }
}

impl<L: VaultLog + Clone + 'static> SyncProtocol<L>
where
    L::Error: std::error::Error + Send + Sync + 'static,
{
    pub fn new(coord: Arc<SyncCoordinator<L>>) -> Self {
        Self { coord }
    }
}

impl<L: VaultLog + Clone + 'static> Clone for SyncProtocol<L>
where
    L::Error: std::error::Error + Send + Sync + 'static,
{
    fn clone(&self) -> Self {
        Self {
            coord: self.coord.clone(),
        }
    }
}

impl<L: VaultLog + Clone + 'static> ProtocolHandler for SyncProtocol<L>
where
    L::Error: std::error::Error + Send + Sync + 'static,
{
    #[allow(refining_impl_trait)]
    fn accept(&self, conn: Connection) -> BoxFuture<'static, Result<(), AcceptError>> {
        let coord = self.coord.clone();
        Box::pin(async move { handle_connection(coord, conn).await })
    }
}

async fn handle_connection<L: VaultLog + Clone + 'static>(
    coord: Arc<SyncCoordinator<L>>,
    conn: Connection,
) -> Result<(), AcceptError>
where
    L::Error: std::error::Error + Send + Sync + 'static,
{
    let remote_id = conn.remote_node_id().map_err(|e| {
        tracing::error!("failed to get remote node id: {e}");
        AcceptError::from(e)
    })?;
    let sender_pk: PublicKey = iroh::from_iroh_public_key(&remote_id);

    let (mut send, mut recv) = conn.accept_bi().await.map_err(|e| {
        tracing::error!("failed to accept bi stream: {e}");
        AcceptError::from(e)
    })?;

    let bytes = recv
        .read_to_end(MAX_MESSAGE)
        .await
        .map_err(|e| AcceptError::from(std::io::Error::other(e)))?;
    let req: WireRequest = bincode::deserialize(&bytes).map_err(|e| {
        tracing::error!("failed to decode WireRequest: {e}");
        let err: Box<dyn std::error::Error + Send + Sync> =
            anyhow!("decode WireRequest: {e}").into();
        AcceptError::from(err)
    })?;

    let reply = dispatch_request(&coord, sender_pk, req).await;

    let reply_bytes = bincode::serialize(&reply).map_err(|e| {
        let err: Box<dyn std::error::Error + Send + Sync> = anyhow!("encode WireReply: {e}").into();
        AcceptError::from(err)
    })?;
    send.write_all(&reply_bytes)
        .await
        .map_err(|e| AcceptError::from(std::io::Error::other(e)))?;
    send.finish()
        .map_err(|e| AcceptError::from(std::io::Error::other(e)))?;
    send.stopped()
        .await
        .map_err(|e| AcceptError::from(std::io::Error::other(e)))?;
    Ok(())
}

// ─── Initiator: IrohPeerSender ─────────────────────────────────────

/// Outbound peer sender backed by an iroh `Endpoint`.
///
/// The `PeerSender` impl (typed `send_head`, `send_probe`, …
/// methods) is generated by the `wire_protocol!` macro in
/// [`crate::wire_protocol`]. Only the transport-level round-trip
/// lives here.
#[derive(Clone)]
pub struct IrohPeerSender {
    endpoint: Endpoint,
}

impl IrohPeerSender {
    pub fn new(endpoint: Endpoint) -> Self {
        Self { endpoint }
    }

    /// Single bidi-stream round-trip used by every macro-generated
    /// `send_*` method. `pub(crate)` so the macro emission in
    /// `wire_protocol.rs` can call it without exposing it on the
    /// crate's public API.
    pub(crate) async fn round_trip(
        &self,
        peer: PublicKey,
        req: WireRequest,
    ) -> anyhow::Result<WireReply> {
        let conn = self
            .endpoint
            .connect(iroh::to_iroh_public_key(&peer), ALPN)
            .await
            .with_context(|| format!("connect to peer {}", peer.to_hex()))?;
        let (mut send, mut recv) = conn.open_bi().await?;

        let req_bytes = bincode::serialize(&req)?;
        send.write_all(&req_bytes).await?;
        send.finish()?;

        let reply_bytes = recv.read_to_end(MAX_MESSAGE).await?;
        let reply: WireReply = bincode::deserialize(&reply_bytes)?;
        Ok(reply)
    }
}
