//! Wire protocol — single source of truth.
//!
//! The [`wire_protocol!`] macro at the bottom of this file takes one
//! row per message: `(VariantName, RequestStruct, ReplyStruct,
//! handler_method)`. From that one declaration it emits:
//!
//! - `pub enum WireRequest { Variant(RequestStruct), … }`
//! - `pub enum WireReply { Variant(ReplyStruct), … }`
//! - `pub trait PeerSender { async fn send_<variant>(…) -> Result<Reply>; … }`
//! - `pub async fn dispatch_request(coord, sender, req) -> WireReply`
//!   — matches on `WireRequest`, calls the matching
//!   `coord.handler_method(sender, req).await`, wraps in the matching
//!   `WireReply` variant.
//! - `impl PeerSender for IrohPeerSender { … }` — round-trips each
//!   typed request through `IrohPeerSender::round_trip` and unwraps
//!   the matching `WireReply` variant.
//!
//! Adding a new message family: append one row to the schema
//! invocation at the bottom, and add the matching `handler_method`
//! on [`SyncCoordinator`](crate::SyncCoordinator). Everything else
//! stays generated.
//!
//! ## Handler shape
//!
//! Every `handler_method` on `SyncCoordinator` must take
//! `(sender: PublicKey, req: RequestStruct)` and return `ReplyStruct`.
//! That uniformity is what makes the macro single-shape. Handlers
//! that don't care about `sender` or `req` accept and discard them.

use crate::iroh_transport::IrohPeerSender;
use crate::messages::{
    Ack, AncestorReply, AncestorRequest, HeadAdvanced, HeadReply, HeadRequest, PingRequest,
    PongReply, ProbeReply, ProbeRequest, ShareOffered,
};

// ---------------------------------------------------------------------
// macro definition
// ---------------------------------------------------------------------

macro_rules! wire_protocol {
    (
        $(
            $variant:ident ( $req:ty, $reply:ty, $handler:ident )
        ),* $(,)?
    ) => {
        paste::paste! {
            // ─── Envelopes ───────────────────────────────────────
            #[derive(Debug, ::serde::Serialize, ::serde::Deserialize)]
            pub enum WireRequest {
                $( $variant($req), )*
            }

            #[derive(Debug, ::serde::Serialize, ::serde::Deserialize)]
            pub enum WireReply {
                $( $variant($reply), )*
            }

            // ─── PeerSender trait ────────────────────────────────
            /// Transport-agnostic peer messaging. One typed method per
            /// wire message; impls are generated by `wire_protocol!`
            /// (real-world: [`IrohPeerSender`]; tests:
            /// [`MemoryPeerSender`](crate::coordinator::MemoryPeerSender)).
            #[::async_trait::async_trait]
            pub trait PeerSender: Send + Sync + 'static {
                $(
                    async fn [<send_ $variant:snake>](
                        &self,
                        peer_id: ::zim_crypto::PublicKey,
                        req: $req,
                    ) -> ::anyhow::Result<$reply>;
                )*
            }

            // ─── Dispatch (responder side) ───────────────────────
            /// Route an incoming [`WireRequest`] into the matching
            /// [`SyncCoordinator`](crate::SyncCoordinator) handler and
            /// wrap the result in [`WireReply`].
            pub async fn dispatch_request<L, P>(
                coord: &::std::sync::Arc<$crate::coordinator::SyncCoordinator<L, P>>,
                sender: ::zim_crypto::PublicKey,
                req: WireRequest,
            ) -> WireReply
            where
                L: $crate::VaultLog + Clone + 'static,
                L::Error: ::std::error::Error + Send + Sync + 'static,
                P: $crate::peers::PeerStore + 'static,
            {
                match req {
                    $(
                        WireRequest::$variant(r) => WireReply::$variant(
                            coord.$handler(sender, r).await,
                        ),
                    )*
                }
            }

            // ─── PeerSender impl for IrohPeerSender ──────────────
            #[::async_trait::async_trait]
            impl PeerSender for IrohPeerSender {
                $(
                    async fn [<send_ $variant:snake>](
                        &self,
                        peer_id: ::zim_crypto::PublicKey,
                        req: $req,
                    ) -> ::anyhow::Result<$reply> {
                        match self.round_trip(peer_id, WireRequest::$variant(req)).await? {
                            WireReply::$variant(r) => Ok(r),
                            other => Err(::anyhow::anyhow!(
                                "unexpected reply to {}: {other:?}",
                                stringify!($variant),
                            )),
                        }
                    }
                )*
            }
        }
    };
}

// ---------------------------------------------------------------------
// schema invocation — the single source of truth
// ---------------------------------------------------------------------

wire_protocol! {
    Head         ( HeadRequest,     HeadReply,     handle_head ),
    Probe        ( ProbeRequest,    ProbeReply,    handle_probe ),
    Ancestor     ( AncestorRequest, AncestorReply, handle_ancestor ),
    HeadAdvanced ( HeadAdvanced,    Ack,           handle_head_advanced ),
    ShareOffered ( ShareOffered,    Ack,           handle_share_offered ),
    Ping         ( PingRequest,     PongReply,     handle_ping ),
}
