//! Viewer authorization endpoints (T-001c).
//!
//! "Viewer" is the identity-system audience for `manifest.shares` — a viewer
//! is a peer whose pubkey appears in the bucket's shares map with an
//! `Owner` role (giving them per-blob-secret access). The mechanics are
//! identical to the existing `share`/`unshare` endpoints; this module exists
//! to surface the viewer naming for the zim-hub identity flow (T-001a/b)
//! without overloading the share/unshare names which still refer to peer
//! sharing in general.
//!
//! Endpoints (flat-route convention matching the rest of `/api/v0/bucket/*`):
//! - `POST /viewers/list` — return current viewers of a bucket.
//! - `POST /viewers/authorize` — add a viewer's pubkey to `manifest.shares`.
//! - `POST /viewers/deauthorise` — remove a viewer's pubkey from `manifest.shares`.
//!   **Known gap**: does not yet trigger re-keying of touched per-node secrets;
//!   a deauthorised viewer that cached blobs can still decrypt them.
//!   Follow-up tracked in T-001c notes.

use axum::extract::{Json, State};
use axum::response::{IntoResponse, Response};
use reqwest::{Client, RequestBuilder, Url};
use serde::{Deserialize, Serialize};
use uuid::Uuid;
use zim_core::fs::FsError;

use zim_crypto::PublicKey;

use crate::http_server::api::client::ApiRequest;
use crate::ServiceState;

// =============================================================
// list
// =============================================================

#[derive(Debug, Clone, Serialize, Deserialize, clap::Args)]
pub struct ListViewersRequest {
    /// Bucket ID
    #[arg(long)]
    pub bucket_id: Uuid,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ListViewersResponse {
    pub bucket_id: Uuid,
    /// Hex-encoded pubkeys of all current viewers (any peer with an entry in
    /// `manifest.shares` — owners and mirrors alike).
    pub viewers: Vec<String>,
}

pub async fn list_handler(
    State(state): State<ServiceState>,
    Json(req): Json<ListViewersRequest>,
) -> Result<impl IntoResponse, ViewerError> {
    let mount = state.peer().mount(req.bucket_id).await?;
    let inner = mount.inner().await;
    let manifest = inner.manifest();
    let viewers: Vec<String> = manifest.shares().keys().cloned().collect();
    Ok((
        http::StatusCode::OK,
        Json(ListViewersResponse {
            bucket_id: req.bucket_id,
            viewers,
        }),
    )
        .into_response())
}

// =============================================================
// authorize
// =============================================================

#[derive(Debug, Clone, Serialize, Deserialize, clap::Args)]
pub struct AuthorizeViewerRequest {
    /// Bucket ID
    #[arg(long)]
    pub bucket_id: Uuid,
    /// Hex-encoded viewer pubkey (Ed25519, 32 bytes → 64 hex)
    #[arg(long)]
    pub viewer_public_key: String,
    /// Mark this viewer as a web-key (browser-resident, not dialable as an
    /// iroh peer). The share gets `dialable: false` so the sync dial loop
    /// skips it. Use for keys generated by zim-wasm in a browser tab.
    #[arg(long, default_value = "false")]
    #[serde(default)]
    pub web_key: bool,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AuthorizeViewerResponse {
    pub bucket_id: Uuid,
    pub viewer_public_key: String,
    pub new_bucket_link: String,
}

pub async fn authorize_handler(
    State(state): State<ServiceState>,
    Json(req): Json<AuthorizeViewerRequest>,
) -> Result<impl IntoResponse, ViewerError> {
    let viewer_pk = PublicKey::from_hex(&req.viewer_public_key)
        .map_err(|e| ViewerError::InvalidPublicKey(e.to_string()))?;

    let mut mount = state.peer().mount(req.bucket_id).await?;
    let dialable = !req.web_key;
    mount.add_share(viewer_pk, dialable).await?;
    let new_link = state.peer().save_mount(&mount).await?;

    tracing::info!(
        "Authorised viewer {} on bucket {} (web_key={}), new link {}",
        req.viewer_public_key,
        req.bucket_id,
        req.web_key,
        new_link.hash()
    );

    Ok((
        http::StatusCode::OK,
        Json(AuthorizeViewerResponse {
            bucket_id: req.bucket_id,
            viewer_public_key: req.viewer_public_key,
            new_bucket_link: new_link.hash().to_string(),
        }),
    )
        .into_response())
}

// =============================================================
// deauthorise
// =============================================================

#[derive(Debug, Clone, Serialize, Deserialize, clap::Args)]
pub struct DeauthoriseViewerRequest {
    /// Bucket ID
    #[arg(long)]
    pub bucket_id: Uuid,
    /// Hex-encoded viewer pubkey
    #[arg(long)]
    pub viewer_public_key: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DeauthoriseViewerResponse {
    pub bucket_id: Uuid,
    pub viewer_public_key: String,
    pub new_bucket_link: String,
}

pub async fn deauthorise_handler(
    State(state): State<ServiceState>,
    Json(req): Json<DeauthoriseViewerRequest>,
) -> Result<impl IntoResponse, ViewerError> {
    let viewer_pk = PublicKey::from_hex(&req.viewer_public_key)
        .map_err(|e| ViewerError::InvalidPublicKey(e.to_string()))?;

    let mount = state.peer().mount(req.bucket_id).await?;
    mount.remove_share(viewer_pk).await?;
    let new_link = state.peer().save_mount(&mount).await?;

    // TODO (T-001c-followup): re-encrypt per-node secrets so a deauthorised
    // viewer who cached blobs cannot decrypt them. Mechanic: rotate the
    // per-node `Secret` on every node the deauthorised viewer was sealed
    // against, re-seal for remaining members, append manifest entry. Out of
    // scope for the v1 endpoint surface.
    tracing::warn!(
        "Deauthorised viewer {} on bucket {} — share removed but per-node \
         secrets are NOT re-keyed yet (T-001c-followup). Cached blob \
         decryption by the deauthorised viewer remains possible.",
        req.viewer_public_key,
        req.bucket_id
    );

    Ok((
        http::StatusCode::OK,
        Json(DeauthoriseViewerResponse {
            bucket_id: req.bucket_id,
            viewer_public_key: req.viewer_public_key,
            new_bucket_link: new_link.hash().to_string(),
        }),
    )
        .into_response())
}

// =============================================================
// shared error type
// =============================================================

#[derive(Debug, thiserror::Error)]
pub enum ViewerError {
    #[error("Invalid public key: {0}")]
    InvalidPublicKey(String),
    #[error("Fs error: {0}")]
    Fs(#[from] FsError),
}

impl IntoResponse for ViewerError {
    fn into_response(self) -> Response {
        match &self {
            ViewerError::InvalidPublicKey(msg) => (
                http::StatusCode::BAD_REQUEST,
                format!("Invalid public key: {}", msg),
            )
                .into_response(),
            ViewerError::Fs(FsError::ShareNotFound) => {
                (http::StatusCode::NOT_FOUND, "Viewer not found".to_string()).into_response()
            }
            ViewerError::Fs(_) => (
                http::StatusCode::INTERNAL_SERVER_ERROR,
                "Unexpected error".to_string(),
            )
                .into_response(),
        }
    }
}

// =============================================================
// client builders for the CLI
// =============================================================

impl ApiRequest for ListViewersRequest {
    type Response = ListViewersResponse;
    fn build_request(self, base_url: &Url, client: &Client) -> RequestBuilder {
        let full_url = base_url.join("/api/v0/bucket/viewers/list").unwrap();
        client.post(full_url).json(&self)
    }
}

impl ApiRequest for AuthorizeViewerRequest {
    type Response = AuthorizeViewerResponse;
    fn build_request(self, base_url: &Url, client: &Client) -> RequestBuilder {
        let full_url = base_url.join("/api/v0/bucket/viewers/authorize").unwrap();
        client.post(full_url).json(&self)
    }
}

impl ApiRequest for DeauthoriseViewerRequest {
    type Response = DeauthoriseViewerResponse;
    fn build_request(self, base_url: &Url, client: &Client) -> RequestBuilder {
        let full_url = base_url.join("/api/v0/bucket/viewers/deauthorise").unwrap();
        client.post(full_url).json(&self)
    }
}
