use std::fmt;

use clap::Args;
use uuid::Uuid;

use crate::cli::ui;
use zim_peer::http_server::api::client::{resolve_bucket, ApiError};
use zim_peer::http_server::api::v0::bucket::viewer::{
    AuthorizeViewerRequest, AuthorizeViewerResponse,
};

#[derive(Args, Debug, Clone)]
pub struct Authorize {
    /// Bucket name or UUID
    pub bucket: String,
    /// Hex-encoded viewer pubkey (Ed25519, 64 hex chars)
    pub viewer_public_key: String,
    /// Mark this viewer as a web-key (browser-resident, not dialable as an
    /// iroh peer). Use for keys generated by zim-wasm in a browser tab.
    #[arg(long)]
    pub web_key: bool,
}

#[derive(Debug)]
pub struct AuthorizeOutput {
    pub bucket_id: Uuid,
    pub viewer_public_key: String,
    pub new_link: String,
}

impl fmt::Display for AuthorizeOutput {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        writeln!(
            f,
            "{}",
            ui::success(
                "Authorised",
                &format!(
                    "viewer {} on bucket {}",
                    self.viewer_public_key, self.bucket_id
                )
            )
        )?;
        write!(f, "{}", ui::label("link", &self.new_link))
    }
}

#[derive(Debug, thiserror::Error)]
pub enum AuthorizeError {
    #[error("API error: {0}")]
    Api(#[from] ApiError),
}

#[async_trait::async_trait]
impl crate::cli::op::Op for Authorize {
    type Error = AuthorizeError;
    type Output = AuthorizeOutput;

    async fn execute(&self, ctx: &crate::cli::op::OpContext) -> Result<Self::Output, Self::Error> {
        let mut client = ctx.client.clone();
        let bucket_id = resolve_bucket(&mut client, &self.bucket).await?;
        let response: AuthorizeViewerResponse = client
            .call(AuthorizeViewerRequest {
                bucket_id,
                viewer_public_key: self.viewer_public_key.clone(),
                web_key: self.web_key,
            })
            .await?;
        Ok(AuthorizeOutput {
            bucket_id: response.bucket_id,
            viewer_public_key: response.viewer_public_key,
            new_link: response.new_bucket_link,
        })
    }
}
