//! `zim hub login` — sign a JWT with the cached device key and print/cache it.
//!
//! Produces an EdDSA-signed compact JWS (RFC 8037) using the device key
//! generated by `zim hub register`. The JWT can be passed as a `Bearer` token
//! to the hub's `/api/v0/*` endpoints once T-017a's JWT verifier middleware
//! ships.

use std::fmt;
use std::path::PathBuf;

use clap::Args;

use crate::cli::ui;
use zim_crypto::PrivateKey;

fn hub_config_dir(hub_url: &str) -> PathBuf {
    let sanitised = hub_url
        .replace("https://", "")
        .replace("http://", "")
        .replace(['/', ':'], "_");
    dirs::config_dir()
        .unwrap_or_else(|| PathBuf::from("."))
        .join("zim")
        .join("hubs")
        .join(sanitised)
}

#[derive(Args, Debug, Clone)]
pub struct Login {
    /// Hub URL (must match a previous `zim hub register --hub <url>`)
    #[arg(long)]
    pub hub: String,

    /// JWT lifetime in seconds (default 3600 = 1 hour)
    #[arg(long, default_value = "3600")]
    pub lifetime: u64,
}

#[derive(Debug)]
pub struct LoginOutput {
    pub hub: String,
    pub token: String,
    pub token_path: PathBuf,
}

impl fmt::Display for LoginOutput {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        writeln!(f, "{}", ui::success("Logged in", &self.hub))?;
        writeln!(
            f,
            "{}",
            ui::label("token", &self.token_path.display().to_string())
        )?;
        write!(
            f,
            "\n  Use with: curl -H 'Authorization: Bearer <token>' ..."
        )
    }
}

#[derive(Debug, thiserror::Error)]
pub enum LoginError {
    #[error("Not registered for hub {0}. Run `zim hub register --hub {0}` first.")]
    NotRegistered(String),
    #[error("IO error: {0}")]
    Io(#[from] std::io::Error),
    #[error("Key error: {0}")]
    Key(String),
}

#[async_trait::async_trait]
impl crate::cli::op::Op for Login {
    type Error = LoginError;
    type Output = LoginOutput;

    async fn execute(&self, _ctx: &crate::cli::op::OpContext) -> Result<Self::Output, Self::Error> {
        let config_dir = hub_config_dir(&self.hub);
        let key_path = config_dir.join("device.key.pem");

        if !key_path.exists() {
            return Err(LoginError::NotRegistered(self.hub.clone()));
        }

        let pem = std::fs::read_to_string(&key_path)?;
        let secret = PrivateKey::from_pem(&pem).map_err(|e| LoginError::Key(e.to_string()))?;
        let public_key = secret.public().to_hex();

        // Build a minimal JWT (EdDSA / ed25519).
        // Header: {"alg":"EdDSA","typ":"JWT","kid":"<pubkey_hex>"}
        // Payload: {"sub":"<pubkey_hex>","iss":"zim-cli","aud":"<hub>","iat":<now>,"exp":<now+lifetime>}
        let now = std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .unwrap()
            .as_secs();

        let header = serde_json::json!({"alg":"EdDSA","typ":"JWT","kid": public_key});
        let payload = serde_json::json!({
            "sub": public_key,
            "iss": "zim-cli",
            "aud": self.hub,
            "iat": now,
            "exp": now + self.lifetime,
        });

        let encode = |v: &serde_json::Value| {
            use base64::Engine;
            base64::engine::general_purpose::URL_SAFE_NO_PAD.encode(serde_json::to_vec(v).unwrap())
        };

        let header_b64 = encode(&header);
        let payload_b64 = encode(&payload);
        let signing_input = format!("{}.{}", header_b64, payload_b64);

        let sig = secret.sign(signing_input.as_bytes());
        let sig_b64 = {
            use base64::Engine;
            base64::engine::general_purpose::URL_SAFE_NO_PAD.encode(sig.to_bytes())
        };

        let token = format!("{}.{}", signing_input, sig_b64);

        // Cache the token for future CLI calls.
        let token_path = config_dir.join("token");
        std::fs::write(&token_path, &token)?;

        Ok(LoginOutput {
            hub: self.hub.clone(),
            token,
            token_path,
        })
    }
}
